// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import localFont from "next/font/local"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { GlobalProvider } from "./context/GlobalContext";

// const inter = Inter({ subsets: ["latin"] });

const aeonik = localFont({
  src: [
    {
      path: "../../public/fonts/aeonik/AeonikTRIAL-Light.woff2",
      weight: "300", //light
      style: "normal"
    },
    {
      path: "../../public/fonts/aeonik/AeonikTRIAL-Regular.woff2",
      weight: "400", //regular
      style: "normal"
    },
    {
      path: "../../public/fonts/aeonik/AeonikTRIAL-Bold.woff2",
      weight: "700", //bold
      style: "normal"
    },

  ],
  variable: "--font-aeonik"
})

const bwmss01 = localFont({
  src: [
    {
      path: "../../public/fonts/BwModelica_SS01/BwModelicaSS01-Regular.woff2",
      weight: "300", //light
      style: "normal"
    },


  ],
  variable: "--font-bwmss01"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${aeonik.variable} ${bwmss01.variable}`}>
        <GlobalProvider>
          <Navbar />
          {children}
          <SpeedInsights />
        </GlobalProvider>
      </body>
    </html>
  );
}
