export const recommendBlogsDataList = [
    {
        title: "SwiGLU: The Activation Function Powering Modern LLMs",
        href: "/blogs/swiglu",
        authorName: "Arjun Jain",
        comments: "10",
        publicationDate: "12 Nov 2024",
        thumbnail: "bg-[#122A5B]",
        description: "",
    },
    {
        title: "Why SiLU Matters: Smooth Activations for Advanced AI Models",
        href: "/blogs/silu",
        authorName: "Arjun Jain",
        comments: "13",
        publicationDate: "10 Nov 2024",
        thumbnail: "bg-silu",
        description: "",
    },
    {
        title: "De-Mystifying Kolmogorov-Arnold Networks (KANs)",
        href: "/blogs/kans",
        authorName: "Rishabh Gupta",
        comments: "12",
        publicationDate: "07 May 2024",
        thumbnail: "bg-kans",
        description: "",
    },
    {
        title: "Mitigating thumbnail Noise in ViTs: Insights from 'Vision Transformers Need Registers'",
        href: "/blogs/vision-transformers",
        authorName: "Arjun Jain",
        comments: "42",
        publicationDate: "05 May 2024",
        thumbnail: "bg-visionTransformers",
        description: "",
    },
    {
        title:
            "Applying Physics-Informed Neural Networks (PINNs): Hands-On Modeling of Lid Driven Cavity",
        href: "/blogs/pinns-hom-lid",
        authorName: "Dhaval Taunk ",
        comments: "43",
        publicationDate: "03 May 2024",
        thumbnail: "bg-pinnslid",
        description: "",
    },
    {
        title: "From Thesis to Reality: The Evolution of GenAI in Creative Content",
        href: "/blogs/thesis-reality",
        authorName: "Arjun Jain",
        comments: "21",
        publicationDate: "01 April 2024",
        thumbnail: "bg-thesis",
        description: "",
    },
    {
        title:
            "Applying Physics-Informed Neural Networks (PINNs): Hands-On Modeling of 2D Plates",
        href: "/blogs/pinns-hom2d",
        authorName: "Dhaval Taunk ",
        comments: "11",
        publicationDate: "22 March 2024",
        thumbnail: "bg-pinns2d",
        description: "",
    },
    {
        title: "Physics Informed Neural Networks (PINNs)",
        href: "/blogs/pinns",
        authorName: "Dhaval Taunk ",
        comments: "21",
        publicationDate: "13 March 2024",
        thumbnail: "bg-pinns",
        description: "",
    },

    {
        title:
            "Mobile-First DVDB (Dart Vector DB): The Pocket-Sized Powerhouse for Your Apps ",
        href: "/blogs/dvdb",
        authorName: "Dhaval Taunk",
        comments: "21",
        publicationDate: "11 March 2024",
        thumbnail: "bg-dvdb",
        description: "",
    },
    {
        title: "Breaking Down Complexity: Focus on Simplicity First",
        href: "/blogs/solving-complex-problem",
        authorName: "Arjun Jain",
        comments: "23",
        publicationDate: "25 March 2024",
        thumbnail: "bg-complexProbHero",
        description: "",
    },
    {
        title: "GANs Simplified: A Quick Guide to Training Generative Adversarial Networks",
        href: "/blogs/gan",
        authorName: "Arjun Jain",
        comments: "33",
        publicationDate: "09 March 2024",
        thumbnail: "bg-gansHero",
        description: "",
    },
    {
        title:
            "Empowering the AI Community: The Role of Open Source in Preventing Monopolies",
        href: "/blogs/ai-dangers-and-preventing-monopolization",
        authorName: "Arjun Jain",
        comments: "20",
        publicationDate: "15 Dec 2023",
        thumbnail: "bg-aiDangers",
        description: "",
    },
    {
        title: "Reflecting on a Journey Through Computer Graphics: Curiosity and Fun",
        href: "/blogs/animated-drawings",
        authorName: "Arjun Jain",
        comments: "15",
        publicationDate: "10 Dec 2023",
        thumbnail: "bg-animatedHero",
        description: "",
    },
    {
        title: "Understanding Neural Network Training: Highlights from My IISc Lecture",
        href: "/blogs/deep-learning",
        authorName: "Arjun Jain",
        comments: "31",
        publicationDate: "3 Dec 2023",
        thumbnail: "bg-deepLearningHero",
        description: "",
    },

    {
        title: "The Evolution of Watermarking: Battling Deepfakes and AI-Generated Imagery ",
        href: "/blogs/authenticity-race",
        authorName: "Arjun Jain",
        comments: "22",
        publicationDate: "21 Nov 2023",
        thumbnail: "bg-authRace",
        description: "",
    },


    {
        title: "RLHF: Shaping Language Models with Human Wisdom ",
        href: "/blogs/rlhf",
        authorName: "Arjun Jain",
        comments: "14",
        publicationDate: "08 Oct 2023",
        thumbnail: "bg-rlhf",
        description: "",
    },
    {
        title: "Crafting Visions: The Magic of DALL-E 3 ",
        href: "/blogs/crafting-visions",
        authorName: "Arjun Jain",
        comments: "21",
        publicationDate: "01 Oct 2023",
        thumbnail: "bg-craftingHero",
        description: "",
    },
    {
        title:
            "Federated Learning: A Game-Changer for Data Privacy and Machine Learning ",
        href: "/blogs/federated-learning",
        authorName: "Arjun Jain",
        comments: "13",
        publicationDate: "01 Sept 2023",
        thumbnail: "bg-federatedHero",
        description: "",
    },
    {
        title: "Overcoming NAS Computational Challenges: Practical Solutions for Researchers ",
        href: "/blogs/nas",
        authorName: "Arjun Jain",
        comments: "19",
        publicationDate: "13 July 2023",
        thumbnail: "bg-nasHero",
        description: "",
    },
    {
        title: "Understanding CL and MIM in Vision Transformers: A Comparative Analysis",
        href: "/blogs/vits",
        authorName: "Arjun Jain",
        comments: "32",
        publicationDate: "18 June 2023",
        thumbnail: "bg-vitsHero",
        description: "",
    },
    {
        title: "The Dilemma: To ML or Not to ML?",
        href: "/blogs/why-ai",
        authorName: "Arjun Jain",
        comments: "33",
        publicationDate: "04 Feb 2021",
        thumbnail: "bg-blog1",
        description: "",
    },
    {
        title: "How to deal with Unknown Classes during classification?",
        href: "/blogs/unknown-classes",
        authorName: "Arjun Jain",
        comments: "12",
        publicationDate: "01 Feb 2021",
        thumbnail: "bg-blog4",
        description: "",
    },

    {
        title: "Oil & Gas EPC - Digitizing P&ID",
        href: "/blogs/oil-gas",
        authorName: "Tarun Kumar",
        comments: "10",
        publicationDate: "03 June 2020",
        thumbnail: "bg-blog3",
        description: "",
    },

];